name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    if: github.repository == 'matrix-org/matrix-rust-sdk'
    runs-on: macos-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Build
        run: cd social-app-ios && swift build --verbose
      - name: Test
        run: cd social-app-ios && swift test --verbose
